services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - shared
    ports:
      - "8080:8080"
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: app
      args:
        DB_PORT: ${DB_PORT}
    image: brunocapitelli/app
    environment:
      DB_CONTAINER_NAME: ${DB_CONTAINER_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - ./app:/app
      - /app/node_modules
    networks: 
      - shared
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: database
    image: brunocapitelli/database
    environment:
      DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - fc_docker_node_db:/var/lib/mysql
    networks: 
      - shared
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${DB_PWD} --silent"]
      retries: 5
      interval: 5s
      timeout: 2s
      start_period: 5s

networks:
  shared:
    driver: bridge

volumes:
  fc_docker_node_db:
    driver: local