#!/bin/bash

mysql -u $DB_USER -p$MYSQL_ROOT_PASSWORD -e "
CREATE DATABASE IF NOT EXISTS ${DB_NAME};

USE ${DB_NAME};

CREATE TABLE IF NOT EXISTS people (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256)
);
"